# EXT:cjnrw/Configuration/RTE/Default.yaml
imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
  config:
    contentsCss: ["EXT:cjnrw/Resources/Public/StyleSheet/rte.css"]
    stylesSet:
      - { name: "Button Primary", element: "a", attributes: { class: "btn btn-primary"} }
      - { name: "Button Secondary", element: "a", attributes: { class: "btn btn-secondary"} }

      - { name: "Download/Externe Seite", element: "a", attributes: { class: "download"} }
      # - { name: "Button Default", element: "a", attributes: { class: "btn btn-default"} }
      # - { name: "Button Link", element: "a", attributes: { class: "btn btn-link"} }
      # - { name: "Button Succes", element: "a", attributes: { class: "btn btn-success"} }
      # - { name: "Button Info", element: "a", attributes: { class: "btn btn-info"} }
      # - { name: "Button Warning", element: "a", attributes: { class: "btn btn-warning"} }
      # - { name: "Button Danger", element: "a", attributes: { class: "btn btn-danger"} }
      # - { name: "Internal Link", element: "a", attributes: { class: "internal-link"} }
      # - { name: "Offset Text", element: "p", attributes: { class: "offset-text"} }
      - { name: "Blaue Box", element:  ['p'], attributes: { class: "bg-primary p-3 rounded shadow text-white"} }
      - { name: ".h1", element: 'p', attributes: { class: "h1"} }
      - { name: ".h2", element: 'p', attributes: { class: "h2"} }
      - { name: ".h3", element: 'p', attributes: { class: "h3"} }
      - { name: ".h2", element: 'h1', attributes: { class: "h2"} }
      - { name: ".h3", element: 'h1', attributes: { class: "h3"} }
      - { name: ".h1", element: 'h2', attributes: { class: "h1"} }
      - { name: ".h3", element: 'h2', attributes: { class: "h3"} }
      - { name: ".h1", element: 'h3', attributes: { class: "h1"} }
      - { name: ".h2", element: 'h3', attributes: { class: "h2"} }
      # - { name: "Box Highlights", element: "p", attributes: { class: "box-highlight"} }
    format_tags: "p;h1;h2;h3;h4;h5;div"
    toolbarGroups:
      - { name: styles }
      - { name: clipboard, groups: [clipboard, undo] }
      - { name: editing,   groups: [find, selection, spellchecker] }
      - { name: links, groups: [links, anchor] }
      - { name: insert }
      - { name: tools }
      - { name: table }
      - { name: tabletools }
      - { name: document,  groups: [ mode, document, doctools ] }
      - { name: others }
      - "/"
      - { name: basicstyles, groups: [ basicstyles, align, cleanup ] }
      - { name: paragraph,   groups: [ list, indent, blocks, align, bidi ] }
     

    justifyClasses:
      - text-left
      - text-center
      - text-right
      - text-justify

    extraPlugins:
      - justify
      - font
      - find
      - bidi


    #RTE default config removes image plugin - restore it:
    removePlugins:
      - image

    removeButtons:
      - Font
      - FontSize

# Allow s and u tag
processing:
  allowTags:
    - s
    - u
